const music = [
    {
        id: 1,
        musicName: 'Cứ chill thôi',
        image: require('../Images/1594611971401_640.jpg'),
        view: 6920,
        favorite: 1509,
        link: require('../songs/CuChillThoi.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 1,
        singerName: 'Suni Hạ Linh',
        singerImage: require('../Images/sunihalinh.jpg'),
        follow: 1289,
        description: 'Không biết mô tả gì',
    },
    {
        id: 2,
        musicName: 'Nơi này có anh',
        image: require('../Images/noinaycoanh.jpg'),
        view: 9832,
        favorite: 7330,
        link: require('../songs//NoiNayCoAnh.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/sontung.jpg'),
        follow: 9080,
        description:
            'Nguyễn Thanh Tùng (sinh ngày 5 tháng 7 năm 1994), thường được biết đến với nghệ danh Sơn Tùng M-TP, là một nam ca sĩ kiêm sáng tác nhạc, rapper và diễn viên người Việt Nam.',
    },
    {
        id: 3,
        musicName: 'Đi về nhà',
        image: require('../Images/divenha.jpg'),
        view: 7889,
        favorite: 3808,
        link: require('../songs/DiVeNha.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/denvau.jpg'),
        follow: 7880,
        description:
            'Nguyễn Đức Cường (sinh ngày 13 tháng 5 năm 1989), thường được biết đến với nghệ danh Đen hay Đen Vâu, là một nam rapper, nhạc sĩ và người dẫn chương trình người Việt Nam. Đen Vâu từng giành được giải Cống hiến và là "một trong số ít nghệ sĩ thành công từ làn sóng underground và âm nhạc indie" của Việt Nam. Anh sở hữu những bài hát đạt hàng triệu lượt xem trên YouTube và là chủ nhân của một số giải thưởng âm nhạc.',
    },
    {
        id: 4,
        musicName: 'Bông hoa đẹp nhất',
        image: require('../Images/f81efd92fa9a3d52eb37f3b867ab9d32.jpg'),
        view: 4660,
        favorite: 2131,
        link: require('../songs/BongHoaDepNhat.mp3'),
        topic: 'Tình Yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 4,
        singerName: 'Quân A.P',
        singerImage: require('../Images/quanap.jpg'),
        follow: 2204,
        description:
            'Quân A.P theo học trường Văn Hóa Nghệ Thuật Quân Đội và hát lại những ca khúc nổi tiếng trên mạng xã hội như "Màu Nước Mắt", "Đừng Ai Nhắc Về Cô Ấy", "Chiều Hôm Ấy"... Anh được người hâm mộ ưu ái gọi là "Hotboy cover".',
    },
    {
        id: 5,
        musicName: 'Người có thương',
        image: require('../Images/ab67616d0000b27356d43cd0de05de88ee177766.jpg'),
        view: 1293,
        favorite: 922,
        link: require('../songs/NguoiCoThuong.mp3'),
        topic: 'Tình Yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 5,
        singerName: 'Đạtkaa',
        singerImage: require('../Images/0cf36f4536237f8efb0b25a83301200b.jpg'),
        follow: 6790,
        description:
            'Là ca sĩ đang rất được giới trẻ, đặc biệt là gen Z yêu thích với những ca khúc như "Dừng Thương", "Hạ Còn Vương Nắng"...',
    },
    {
        id: 6,
        musicName: 'Bài này chill phết',
        image: require('../Images/7f6841139a16e64d39d877ba6566da9c.jpg'),
        view: 5888,
        favorite: 4928,
        link: require('../songs/BaiNayChillPhet.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/denvau.jpg'),
        follow: 7880,
        description:
            'Nguyễn Đức Cường (sinh ngày 13 tháng 5 năm 1989), thường được biết đến với nghệ danh Đen hay Đen Vâu, là một nam rapper, nhạc sĩ và người dẫn chương trình người Việt Nam. Đen Vâu từng giành được giải Cống hiến và là "một trong số ít nghệ sĩ thành công từ làn sóng underground và âm nhạc indie" của Việt Nam. Anh sở hữu những bài hát đạt hàng triệu lượt xem trên YouTube và là chủ nhân của một số giải thưởng âm nhạc.',
    },
    {
        id: 7,
        musicName: 'Shadow of the sun',
        image: require('../Images/maxresdefault (1).jpg'),
        view: 6183,
        favorite: 3222,
        link: require('../songs/ShadowOfTheSun .mp3'),
        topic: 'Động Lực',
        quocGia: 'Âu Mỹ',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 6,
        singerName: 'Max Elto',
        singerImage: require('../Images/tx.jpg'),
        follow: 5406,
        description:
            'Max Elto, trước đây gọi là Taped Rai, là một bộ đôi ca sĩ người CupiThụy Điển gồm Tom Liljegren và Alexander Ryberg. Họ được biết đến nhiều nhất khi góp giọng cho đĩa đơn "Just One Last Time" của David Guetta và phát hành đĩa đơn đầu tay "Shadow of the Sun" năm 2013.',
    },
    {
        id: 8,
        musicName: 'Cupid',
        image: require('../Images/613rUBFQ4zL._UF1000,1000_QL80_.jpg'),
        view: 5717,
        favorite: 2487,
        link: require('../songs/FIFTYFIFTY.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Hàn Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 7,
        singerName: 'FIFTY FIFTY',
        singerImage: require('../Images/ftft.png'),
        follow: 3271,
        description:
            'Fifty Fifty (tiếng Hàn: 피프티 피프티; RR: Pipeuti Pipeuti) là một nhóm nhạc nữ của Hàn Quốc được thành lập vào năm 2022 bao gồm 4 thành viên là Sio, Aran, Saena và Keena. Nhóm nằm dưới sự quản lí của Attrakt, một hãng thu âm độc lập, nhóm chính thức có màn ra mắt vào tháng 11/2022 với EP đầu tay The Fifty. Nhóm được biết đến rộng rãi với công chúng toàn thế giới với bản hit " Cupid " được ra mắt vào tháng 2/2023[1]. Nhờ bản hit này, Fifty Fifty đã trở thành nhóm nhạc nữ lọt vào BXH Billboard[2] và UK Singles Chart[3] nhanh nhất trong lịch sử K-pop khi chỉ mới ra mắt được 4 tháng. Ngoài ra, còn là nhóm nhạc nữ K-pop đầu tiên lọt vào Top 10 của UK Charts [4].',
    },
    {
        id: 9,
        musicName: 'Giày cao gót màu đỏ',
        image: require('../Images/maxresdefault (3).jpg'),
        view: 6648,
        favorite: 4462,
        link: require('../songs/GiayCaoGotMauDo-ThaiKienNhaTanyaChua-6178396.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 8,
        singerName: 'Thái Kiệt Nhã',
        singerImage: require('../Images/26815327_1768633973168696_2615565288466836166_n.jpg'),
        follow: 4843,
        description:
            'Thái Kiện Nhã, nữ ca sĩ tài hoa Xinh-ga-po đã làm rung động biết bao trái tim với giọng truyền cảm . Trước khi trở thành ca sĩ hợp đồng với một công ty nào đó, cô từng hát ở các quán ba , nhà hàng ở Xinh-ga-po. Sau khi chính thức ký hợp đồng với Công ty Warner , cô phát hành Album đầu tiên vào năm 1999 mang tên "Nhịp thở", trở thành gương mặt mới trong làng ca nhạc với ca khúc cùng tên Album. Nhưng sau đó , chuyện chia tay với người yêu khiến cô từng một dạo từ bỏ ánh đèn sân khấu . Năm 2003 , cô dày công đưa ra Album tiếng Hoa mang tên " Người không quen" , mỗi bài ca khúc trong Album này đều rung động trái tim người nghe , giành được doanh thu khá cao .',
    },
    {
        id: 10,
        musicName: 'Hit me up',
        image: require('../Images/loi-bai-hat-hit-me-up-binz-xuan-dan-3.jpg'),
        view: 7628,
        favorite: 5462,
        link: require('../songs/HitMeUp.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Trẻ',
        vip: false,
        singerId: 9,
        singerName: 'Xuân Đan',
        singerImage: require('../Images/photo-1-16970956331761075803068.webp'),
        follow: 3843,
        description: 'Chào em! anh là Xuân Đan',
    },
    {
        id: 11,
        musicName: 'Âm thầm bên em',
        image: require('../Images/1450155936245_500.jpg'),
        view: 7666,
        favorite: 5542,
        link: require('../songs/AmThamBenEm.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/sontung.jpg'),
        follow: 9080,
        description:
            'Nguyễn Thanh Tùng (sinh ngày 5 tháng 7 năm 1994), thường được biết đến với nghệ danh Sơn Tùng M-TP, là một nam ca sĩ kiêm sáng tác nhạc, rapper và diễn viên người Việt Nam.',
    },
    {
        id: 12,
        musicName: 'Là Anh / 是你',
        image: require('../Images/1676004847611_640.jpg'),
        view: 8766,
        favorite: 6598,
        link: require('../songs/LaAnh-MongNhienMengRan-7839255.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 10,
        singerName: 'Mộng Nhiên / 梦然',
        singerImage: require('../Images/mongnhien.jpg'),
        follow: 7080,
        description:
            'Mộng Nhiên là ca sỹ tự do, sinh năm 1989, là cô gái đến từ khu tự trị Nội Mông ( Trung Quốc). Lên lớp 11, cô được nhận vào Nhạc viện Thẩm Dương với điểm số xuất sắc. Khi là sinh viên, cô đã nhiều lần sáng tác nhạc cho các ca sĩ và khi tốt nghiệp đại học, cô bước vào làng âm nhạc với tư cách là một ca sĩ thực thụ. Vào năm 2012, cô nổi tiếng khi ra mắt bài hát “Love you Love me”.',
    },
    {
        id: 13,
        musicName: 'China-X',
        image: require('../Images/artworks-000173690932-nqyx6n-t500x500.jpg'),
        view: 5306,
        favorite: 4898,
        link: require('../songs/ChinaX .mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description:
            'Từ Mộng Viên là một ca sĩ, nhạc sĩ người Trung Quốc. Cô sinh ngày 20 tháng 10 năm 1993 tại thành phố Vũ Hán, tỉnh Hồ Bắc, Trung Quốc. Từ Mộng Viên bắt đầu học nhạc từ nhỏ, và có niềm đam mê với âm nhạc từ khi còn rất sớm. Cô đã tham gia nhiều cuộc thi âm nhạc và đạt được nhiều giải thưởng. Năm 2016, cô ra mắt album đầu tiên của mình mang tên "China-X". Album đã nhận được nhiều phản hồi tích cực từ khán giả, và giúp cô trở thành một trong những ca sĩ trẻ nổi tiếng nhất Trung Quốc.',
    },
    {
        id: 14,
        musicName: 'Rise UP',
        image: require('../Images/ab67616d00001e02043a40737b9cded403f02ee4.jpg'),
        view: 4306,
        favorite: 2898,
        link: require('../songs/RiseUp.mp3'),
        topic: 'Sôi động',
        quocGia: 'Âu Mỹ',
        theLoai: 'EDM',
        vip: true,
        singerId: 12,
        singerName: 'TheFatRat',
        singerImage: require('../Images/1475049690234_600.jpg'),
        follow: 8680,
        description:
            'Là nhà sản xuất âm nhạc và DJ người Đức với sở trường là thể loại "glitch-hop", các bản hit nổi bật là "Fly Away", "Unity" và "Monody".',
    },
    {
        id: 15,
        musicName: 'Suýt nữa thì',
        image: require('../Images/c2475264a30999a45a3c8bcf0e5f090d.jpg'),
        view: 5376,
        favorite: 3129,
        link: require('../songs/SuytNuaThi-Andiez-7625469.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 13,
        singerName: 'Andiez',
        singerImage: require('../Images/andiez.jpg'),
        follow: 4615,
        description:
            'Đam mê âm nhạc từ bé, bắt đầu hát và sáng tác từ năm lớp 10. Năm 2017, Andiez sáng tác và trình bày ca khúc "Một Phút", ca khúc trở thành hiện tượng trên mạng xã hội.',
    },
    {
        id: 16,
        musicName: 'Tự sự',
        image: require('../Images/TuSu.jpg'),
        view: 3376,
        favorite: 1429,
        link: require('../songs/TuSuQuaBenLamChiOst-Orange-7564924.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 14,
        singerName: 'Orange',
        singerImage: require('../Images/Orange.jpg'),
        follow: 4915,
        description:
            'Là ca sĩ có chất giọng đầy nội lực cùng gu âm nhạc trẻ trung được đông đảo khán giả trẻ yêu thích sau ca khúc debut “Người Lạ Ơi”. Hiện Orange là một trong số nữ ca sĩ có khả năng sáng tác tốt thuộc thế hệ Gen Z nổi bật tại Việt Nam',
    },
    {
        id: 17,
        musicName: 'Close to the sun',
        image: require('../Images/1568960889223_640.jpg'),
        view: 7306,
        favorite: 3898,
        link: require('../songs/CloseToTheSun.mp3'),
        topic: 'Sôi động',
        quocGia: 'Âu Mỹ',
        theLoai: 'EDM',
        vip: true,
        singerId: 12,
        singerName: 'TheFatRat',
        singerImage: require('../Images/1475049690234_600.jpg'),
        follow: 8680,
        description:
            'Là nhà sản xuất âm nhạc và DJ người Đức với sở trường là thể loại "glitch-hop", các bản hit nổi bật là "Fly Away", "Unity" và "Monody".',
    },
    {
        id: 18,
        musicName: 'China-P',
        image: require('../Images/artworks-000192779544-0vlf0o-t240x240.jpg'),
        view: 2331,
        favorite: 1245,
        link: require('../songs/ChinaP .mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description:
            'Từ Mộng Viên là một ca sĩ, nhạc sĩ người Trung Quốc. Cô sinh ngày 20 tháng 10 năm 1993 tại thành phố Vũ Hán, tỉnh Hồ Bắc, Trung Quốc. Từ Mộng Viên bắt đầu học nhạc từ nhỏ, và có niềm đam mê với âm nhạc từ khi còn rất sớm. Cô đã tham gia nhiều cuộc thi âm nhạc và đạt được nhiều giải thưởng. Năm 2016, cô ra mắt album đầu tiên của mình mang tên "China-X". Album đã nhận được nhiều phản hồi tích cực từ khán giả, và giúp cô trở thành một trong những ca sĩ trẻ nổi tiếng nhất Trung Quốc.',
    },
    {
        id: 19,
        musicName: 'Thằng điên',
        image: require('../Images/9d5c56a277a06a48ec7956a4fd17e4c1.jpg'),
        view: 8620,
        favorite: 6659,
        link: require('../songs/ThangDien.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 15,
        singerName: 'JustaTee',
        singerImage: require('../Images/justatee.jpg'),
        follow: 5691,
        description:
            'Nguyễn Thanh Tuấn (sinh ngày 1 tháng 11 năm 1991), thường được biết đến với nghệ danh JustaTee hay JayTee, là một nam ca sĩ, nhạc sĩ sáng tác ca khúc, rapper kiêm nhà sản xuất thu âm người Việt Nam. Là một trong những ca sĩ nổi bật trong dòng nhạc R&B, anh từng được đề cử một giải Cống hiến, cũng như từng giành giải Zing Music Awards.',
    },
    {
        id: 20,
        musicName: 'Ngày trước sợ',
        image: require('../Images/f9075b77e14e65e6aeef780855d438d8.jpg'),
        view: 5328,
        favorite: 3171,
        link: require('../songs/NgayTruocSo.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc trẻ',
        vip: true,
        singerId: 16,
        singerName: 'Vu Đông Nhiên',
        singerImage: require('../Images/4e80a3a495f4cc82d85cf8904b1dc0e5.jpg'),
        follow: 4859,
        description: 'Không biết mô tả gì',
    },
    {
        id: 29,
        musicName: 'Chúng ta của hiện tại',
        image: require('../Images/f0c6b74652e9ed643f3183c7617aaa30.jpg'),
        view: 8327,
        favorite: 6732,
        link: require('../songs/ChungTaCuHienTai.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/sontung.jpg'),
        follow: 9080,
        description:
            'Nguyễn Thanh Tùng (sinh ngày 5 tháng 7 năm 1994), thường được biết đến với nghệ danh Sơn Tùng M-TP, là một nam ca sĩ kiêm sáng tác nhạc, rapper và diễn viên người Việt Nam.',
    },
    {
        id: 22,
        musicName: 'Lối nhỏ',
        image: require('../Images/2d0bf08b1ddaa07bae28208796316571.jpg'),
        view: 6281,
        favorite: 3016,
        link: require('../songs/LoiNho.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/denvau.jpg'),
        follow: 7880,
        description:
            'Nguyễn Đức Cường (sinh ngày 13 tháng 5 năm 1989), thường được biết đến với nghệ danh Đen hay Đen Vâu, là một nam rapper, nhạc sĩ và người dẫn chương trình người Việt Nam. Đen Vâu từng giành được giải Cống hiến và là "một trong số ít nghệ sĩ thành công từ làn sóng underground và âm nhạc indie" của Việt Nam. Anh sở hữu những bài hát đạt hàng triệu lượt xem trên YouTube và là chủ nhân của một số giải thưởng âm nhạc.',
    },
    {
        id: 23,
        musicName: 'China-PiPa',
        image: require('../Images/artworks-nKt3cCTT7aUzNkJa-A9f4PQ-t500x500.jpg'),
        view: 3957,
        favorite: 1487,
        link: require('../songs/ChinaPiPa.mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description:
            'Từ Mộng Viên là một ca sĩ, nhạc sĩ người Trung Quốc. Cô sinh ngày 20 tháng 10 năm 1993 tại thành phố Vũ Hán, tỉnh Hồ Bắc, Trung Quốc. Từ Mộng Viên bắt đầu học nhạc từ nhỏ, và có niềm đam mê với âm nhạc từ khi còn rất sớm. Cô đã tham gia nhiều cuộc thi âm nhạc và đạt được nhiều giải thưởng. Năm 2016, cô ra mắt album đầu tiên của mình mang tên "China-X". Album đã nhận được nhiều phản hồi tích cực từ khán giả, và giúp cô trở thành một trong những ca sĩ trẻ nổi tiếng nhất Trung Quốc.',
    },
    {
        id: 24,
        musicName: 'Nàng thơ',
        image: require('../Images/nang-tho.jpeg'),
        view: 6271,
        favorite: 3694,
        link: require('../songs/NangTho.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 17,
        singerName: 'Hoàng Dũng',
        singerImage: require('../Images/Ca-sy-hoang-dung-1024x576.jpg'),
        follow: 4869,
        description:
            'Hoàng Dũng là ca nhạc sĩ 9x được yêu thích qua những bản nhạc nhẹ nhàng, du dương và đậm chất "thơ". Với lối tư duy văn minh trong âm nhạc, khả năng sáng tác và giọng hát nội lực, Hoàng Dũng được đánh giá là một nghệ sĩ tiềm năng và đang dần khẳng định phong cách cũng như vị trí của mình trong lớp nghệ sĩ trẻ tại Việt Nam.',
    },
    {
        id: 25,
        musicName: 'Chờ anh nhé',
        image: require('../Images/a5770da425db0bd4d1c397badb944075_1465443445.jpg'),
        view: 4534,
        favorite: 2101,
        link: require('../songs/ChoAnhNhe.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 17,
        singerName: 'Hoàng Dũng',
        singerImage: require('../Images/Ca-sy-hoang-dung-1024x576.jpg'),
        follow: 4869,
        description:
            'Hoàng Dũng là ca nhạc sĩ 9x được yêu thích qua những bản nhạc nhẹ nhàng, du dương và đậm chất "thơ". Với lối tư duy văn minh trong âm nhạc, khả năng sáng tác và giọng hát nội lực, Hoàng Dũng được đánh giá là một nghệ sĩ tiềm năng và đang dần khẳng định phong cách cũng như vị trí của mình trong lớp nghệ sĩ trẻ tại Việt Nam.',
    },
    {
        id: 26,
        musicName: 'Chuyện đôi ta',
        image: require('../Images/560a638ee414c3374a29d0ac5c372b9f.jpg'),
        view: 6722,
        favorite: 3511,
        link: require('../songs/ChuyenDoiTa.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 18,
        singerName: 'Emcee L',
        singerImage: require('../Images/photo-4-16992776047111594909251.webp'),
        follow: 3254,
        description:
            'Nổi tiếng trước đó nhờ vào những ca khúc tự mình sáng tác và trình diễn như: Chỉ Là Số Hai, Thuốc Độc, Dưới Hiên Nhà, … Emcee L khiến khán giả nhớ đến mình nhờ vào những ngôn từ sắc bén cộng với sự đa tài của mình khi anh có thể làm rất nhiều công đoạn như sáng tác, trình diễn và thậm chí là hòa âm, phối khí cho tác phẩm của mình ',
    },
    {
        id: 27,
        musicName: 'Đã lỡ yêu em nhiều',
        image: require('../Images/dae7488899bf6ee55f4127cb6a889391_1510557125.jpg'),
        view: 5184,
        favorite: 3769,
        link: require('../songs/DaLoYeuEmNhieu.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 15,
        singerName: 'JustaTee',
        singerImage: require('../Images/justatee.jpg'),
        follow: 5691,
        description:
            'Nguyễn Thanh Tuấn (sinh ngày 1 tháng 11 năm 1991), thường được biết đến với nghệ danh JustaTee hay JayTee, là một nam ca sĩ, nhạc sĩ sáng tác ca khúc, rapper kiêm nhà sản xuất thu âm người Việt Nam. Là một trong những ca sĩ nổi bật trong dòng nhạc R&B, anh từng được đề cử một giải Cống hiến, cũng như từng giành giải Zing Music Awards.',
    },
    {
        id: 28,
        musicName: 'Tình nhân ơi',
        image: require('../Images/1545578861465_640.jpg'),
        view: 5473,
        favorite: 4526,
        link: require('../songs/tinhnhanoi.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 14,
        singerName: 'Orange',
        singerImage: require('../Images/Orange.jpg'),
        follow: 4915,
        description:
            'Là ca sĩ có chất giọng đầy nội lực cùng gu âm nhạc trẻ trung được đông đảo khán giả trẻ yêu thích sau ca khúc debut “Người Lạ Ơi”. Hiện Orange là một trong số nữ ca sĩ có khả năng sáng tác tốt thuộc thế hệ Gen Z nổi bật tại Việt Nam',
    },
    {
        id: 21,
        musicName: 'Khuôn mặt đáng thương',
        image: require('../Images/2e6cc492ff910c1804673bc5a21be89e.jpg'),
        view: 7646,
        favorite: 5998,
        link: require('../songs/khuanmatdangthuong.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/sontung.jpg'),
        follow: 9080,
        description:
            'Nguyễn Thanh Tùng (sinh ngày 5 tháng 7 năm 1994), thường được biết đến với nghệ danh Sơn Tùng M-TP, là một nam ca sĩ kiêm sáng tác nhạc, rapper và diễn viên người Việt Nam.',
    },
];
export default music;
