const music = [
    {
        id: 1,
        musicName: 'Cứ chill thôi',
        image: require('../Images/1594611971401_640.jpg'),
        view: 6920,
        favorite: 1509,
        link: require('../songs/CuChillThoi.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 1,
        singerName: 'Suni Hạ Linh',
        singerImage: require('../Images/e5132977d0df155b73a7637283fb1499.jpg'),
        follow: 1289,
        description: 'Không biết mô tả gì',
    },
    {
        id: 2,
        musicName: 'Nơi này có anh',
        image: require('../Images/noinaycoanh.jpg'),
        view: 9832,
        favorite: 7330,
        link: require('../songs//NoiNayCoAnh.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/fbf16d7352a3eea6be8cf5d4b217516d.jpg'),
        follow: 9080,
        description:
            'Nguyễn Thanh Tùng (sinh ngày 5 tháng 7 năm 1994), thường được biết đến với nghệ danh Sơn Tùng M-TP, là một nam ca sĩ kiêm sáng tác nhạc, rapper và diễn viên người Việt Nam.',
    },
    {
        id: 3,
        musicName: 'Đi về nhà',
        image: require('../Images/divenha.jpg'),
        view: 7889,
        favorite: 3808,
        link: require('../songs/DiVeNha.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/4d347aacb2be84d868dd6d25bb4aa503.jpg'),
        follow: 7880,
        description: 'Không biết mô tả gì',
    },
    {
        id: 4,
        musicName: 'Bông hoa đẹp nhất',
        image: require('../Images/f81efd92fa9a3d52eb37f3b867ab9d32.jpg'),
        view: 4660,
        favorite: 2131,
        link: require('../songs/BongHoaDepNhat.mp3'),
        topic: 'Tình Yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 4,
        singerName: 'Quân A.P',
        singerImage: require('../Images/65c36b8d4965ed39880d480df406408b.jpg'),
        follow: 2204,
        description: 'Không biết mô tả gì',
    },
    {
        id: 5,
        musicName: 'Người có thương',
        image: require('../Images/ab67616d0000b27356d43cd0de05de88ee177766.jpg'),
        view: 1293,
        favorite: 922,
        link: require('../songs/NguoiCoThuong.mp3'),
        topic: 'Tình Yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 5,
        singerName: 'Đạtkaa',
        singerImage: require('../Images/0cf36f4536237f8efb0b25a83301200b.jpg'),
        follow: 6790,
        description: 'Không biết mô tả gì',
    },
    {
        id: 6,
        musicName: 'Bài này chill phết',
        image: require('../Images/7f6841139a16e64d39d877ba6566da9c.jpg'),
        view: 5888,
        favorite: 4928,
        link: require('../songs/BaiNayChillPhet.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/4d347aacb2be84d868dd6d25bb4aa503.jpg'),
        follow: 7880,
        description: 'Không biết mô tả gì',
    },
    {
        id: 7,
        musicName: 'Shadow of the sun',
        image: require('../Images/maxresdefault (1).jpg'),
        view: 6183,
        favorite: 3222,
        link: require('../songs/ShadowOfTheSun .mp3'),
        topic: 'Động Lực',
        quocGia: 'Âu Mỹ',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 6,
        singerName: 'Max Elto',
        singerImage: require('../Images/tx.jpg'),
        follow: 5406,
        description: 'Không biết mô tả gì',
    },
    {
        id: 8,
        musicName: 'Cupid',
        image: require('../Images/maxresdefault (2).jpg'),
        view: 5717,
        favorite: 2487,
        link: require('../songs/FIFTYFIFTY.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Hàn Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 7,
        singerName: 'FIFTY FIFTY',
        singerImage: require('../Images/ftft.png'),
        follow: 3271,
        description: 'Không biết mô tả gì',
    },
    {
        id: 9,
        musicName: 'Giày cao gót màu đỏ',
        image: require('../Images/maxresdefault (3).jpg'),
        view: 6648,
        favorite: 4462,
        link: require('../songs/GiayCaoGotMauDo-ThaiKienNhaTanyaChua-6178396.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 8,
        singerName: 'Thái Kiệt Nhã',
        singerImage: require('../Images/26815327_1768633973168696_2615565288466836166_n.jpg'),
        follow: 4843,
        description: 'Không biết mô tả gì',
    },
    {
        id: 10,
        musicName: 'Hit me up',
        image: require('../Images/loi-bai-hat-hit-me-up-binz-xuan-dan-3.jpg'),
        view: 7628,
        favorite: 5462,
        link: require('../songs/HitMeUp.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Trẻ',
        vip: false,
        singerId: 9,
        singerName: 'Xuân Đan',
        singerImage: require('../Images/photo-1-16970956331761075803068.webp'),
        follow: 3843,
        description: 'Không biết mô tả gì',
    },
    {
        id: 11,
        musicName: 'Âm thầm bên em',
        image: require('../Images/1450155936245_500.jpg'),
        view: 7666,
        favorite: 5542,
        link: require('../songs/AmThamBenEm.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/fbf16d7352a3eea6be8cf5d4b217516d.jpg'),
        follow: 9080,
        description: 'Không biết mô tả gì',
    },
    {
        id: 12,
        musicName: 'Là Anh / 是你',
        image: require('../Images/1676004847611_640.jpg'),
        view: 8766,
        favorite: 6598,
        link: require('../songs/LaAnh-MongNhienMengRan-7839255.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc Trẻ',
        vip: true,
        singerId: 10,
        singerName: 'Mộng Nhiên / 梦然',
        singerImage: require('../Images/90e63f505524e9919fbf1a85e01df83e.jpg'),
        follow: 7080,
        description: 'Không biết mô tả gì',
    },
    {
        id: 13,
        musicName: 'China-X',
        image: require('../Images/artworks-000173690932-nqyx6n-t500x500.jpg'),
        view: 5306,
        favorite: 4898,
        link: require('../songs/ChinaX .mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description: 'Không biết mô tả gì',
    },
    {
        id: 14,
        musicName: 'Rise UP',
        image: require('../Images/ab67616d00001e02043a40737b9cded403f02ee4.jpg'),
        view: 4306,
        favorite: 2898,
        link: require('../songs/RiseUp.mp3'),
        topic: 'Sôi động',
        quocGia: 'Âu Mỹ',
        theLoai: 'EDM',
        vip: true,
        singerId: 12,
        singerName: 'TheFatRat',
        singerImage: require('../Images/1475049690234_600.jpg'),
        follow: 8680,
        description: 'Không biết mô tả gì',
    },
    {
        id: 15,
        musicName: 'Suýt nữa thì',
        image: require('../Images/c2475264a30999a45a3c8bcf0e5f090d.jpg'),
        view: 5376,
        favorite: 3129,
        link: require('../songs/SuytNuaThi-Andiez-7625469.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 13,
        singerName: 'Andiez',
        singerImage: require('../Images/75ae579a51cfa505932f59397eac8d69.jpg'),
        follow: 4615,
        description: 'Không biết mô tả gì',
    },
    {
        id: 16,
        musicName: 'Tự sự',
        image: require('../Images/TuSu.jpg'),
        view: 3376,
        favorite: 1429,
        link: require('../songs/TuSuQuaBenLamChiOst-Orange-7564924.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 14,
        singerName: 'Orange',
        singerImage: require('../Images/ace9cb5831bbc7e8cc90d8e7432e4b3a.jpg'),
        follow: 4915,
        description: 'Không biết mô tả gì',
    },
    {
        id: 17,
        musicName: 'Close to the sun',
        image: require('../Images/1568960889223_640.jpg'),
        view: 7306,
        favorite: 3898,
        link: require('../songs/CloseToTheSun.mp3'),
        topic: 'Sôi động',
        quocGia: 'Âu Mỹ',
        theLoai: 'EDM',
        vip: true,
        singerId: 12,
        singerName: 'TheFatRat',
        singerImage: require('../Images/1475049690234_600.jpg'),
        follow: 8680,
        description: 'Không biết mô tả gì',
    },
    {
        id: 18,
        musicName: 'China-P',
        image: require('../Images/artworks-000192779544-0vlf0o-t240x240.jpg'),
        view: 2331,
        favorite: 1245,
        link: require('../songs/ChinaP .mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description: 'Không biết mô tả gì',
    },
    {
        id: 19,
        musicName: 'Thằng điên',
        image: require('../Images/9d5c56a277a06a48ec7956a4fd17e4c1.jpg'),
        view: 8620,
        favorite: 6659,
        link: require('../songs/ThangDien.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 15,
        singerName: 'JustaTee',
        singerImage: require('../Images/33b54115d5b1149f5ac51b4038ef62c7.jpg'),
        follow: 5691,
        description: 'Không biết mô tả gì',
    },
    {
        id: 20,
        musicName: 'Ngày trước sợ',
        image: require('../Images/f9075b77e14e65e6aeef780855d438d8.jpg'),
        view: 5328,
        favorite: 3171,
        link: require('../songs/NgayTruocSo.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc trẻ',
        vip: true,
        singerId: 16,
        singerName: 'Vu Đông Nhiên',
        singerImage: require('../Images/4e80a3a495f4cc82d85cf8904b1dc0e5.jpg'),
        follow: 4859,
        description: 'Không biết mô tả gì',
    },
    {
        id: 21,
        musicName: 'Chúng ta của hiện tại',
        image: require('../Images/f0c6b74652e9ed643f3183c7617aaa30.jpg'),
        view: 8327,
        favorite: 6732,
        link: require('../songs/ChungTaCuHienTai.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 2,
        singerName: 'Sơn Tùng M-TP',
        singerImage: require('../Images/fbf16d7352a3eea6be8cf5d4b217516d.jpg'),
        follow: 9080,
        description: 'Không biết mô tả gì',
    },
    {
        id: 22,
        musicName: 'Lối nhỏ',
        image: require('../Images/2d0bf08b1ddaa07bae28208796316571.jpg'),
        view: 6281,
        favorite: 3016,
        link: require('../songs/LoiNho.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc Rap',
        vip: false,
        singerId: 3,
        singerName: 'Đen Vâu',
        singerImage: require('../Images/4d347aacb2be84d868dd6d25bb4aa503.jpg'),
        follow: 7880,
        description: 'Không biết mô tả gì',
    },
    {
        id: 23,
        musicName: 'China-PiPa',
        image: require('../Images/artworks-nKt3cCTT7aUzNkJa-A9f4PQ-t500x500.jpg'),
        view: 3957,
        favorite: 1487,
        link: require('../songs/ChinaPiPa.mp3'),
        topic: 'Sôi động',
        quocGia: 'Trung Quốc',
        theLoai: 'Nhạc không lời',
        vip: true,
        singerId: 11,
        singerName: 'Từ Mộng Viên',
        singerImage: require('../Images/13b193b26d3bc7bbc4da0b4f9dac9455.jpg'),
        follow: 5680,
        description: 'Không biết mô tả gì',
    },
    {
        id: 24,
        musicName: 'Nàng thơ',
        image: require('../Images/nang-tho.jpeg'),
        view: 6271,
        favorite: 3694,
        link: require('../songs/NangTho.mp3'),
        topic: 'Thư giãn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 17,
        singerName: 'Hoàng Dũng',
        singerImage: require('../Images/Ca-sy-hoang-dung-1024x576.jpg'),
        follow: 4869,
        description: 'Không biết mô tả gì',
    },
    {
        id: 25,
        musicName: 'Chờ anh nhé',
        image: require('../Images/a5770da425db0bd4d1c397badb944075_1465443445.jpg'),
        view: 4534,
        favorite: 2101,
        link: require('../songs/ChoAnhNhe.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 17,
        singerName: 'Hoàng Dũng',
        singerImage: require('../Images/Ca-sy-hoang-dung-1024x576.jpg'),
        follow: 4869,
        description: 'Không biết mô tả gì',
    },
    {
        id: 26,
        musicName: 'Chuyện đôi ta',
        image: require('../Images/560a638ee414c3374a29d0ac5c372b9f.jpg'),
        view: 6722,
        favorite: 3511,
        link: require('../songs/ChuyenDoiTa.mp3'),
        topic: 'Giai điệu buồn',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 18,
        singerName: 'Emcee L',
        singerImage: require('../Images/photo-1-16970956331761075803068.webp'),
        follow: 3254,
        description: 'Không biết mô tả gì',
    },
    {
        id: 27,
        musicName: 'Đã lỡ yêu em nhiều',
        image: require('../Images/dae7488899bf6ee55f4127cb6a889391_1510557125.jpg'),
        view: 5184,
        favorite: 3769,
        link: require('../songs/DaLoYeuEmNhieu.mp3'),
        topic: 'Tình yêu',
        quocGia: 'Việt Nam',
        theLoai: 'Nhạc trẻ',
        vip: false,
        singerId: 15,
        singerName: 'JustaTee',
        singerImage: require('../Images/33b54115d5b1149f5ac51b4038ef62c7.jpg'),
        follow: 5691,
        description: 'Không biết mô tả gì',
    },
];
export default music;
